#define NUM_LAYERS		 	3
#define LEARNING_RATE	 	0.700
#define CONNECTION_RATE	 	1.00
#define NETWORK_TYPE		 0
#define LEARNING_MOMENTUM	 0
#define TRAINING_ALGORITHM	 2
#define TRAIN_ERROR_FUNC	 1
#define TRAIN_STOP_FUNC		 1

#define CASCADE_OUTPUT_CHANGE_FRACTION 	 0.010
#define QUICKDROP_DECAY					-0.000100
#define QUICKDROP_MU					1.75
#define RPROP_INCREASE_FACTOR			1.2
#define RPROP_DECREASE_FACTOR			0.5
#define RPROP_DELTAMIN					0
#define RPROP_DELTAMAX		 			50
#define RPROP_DELTAZERO					0.1
#define CASCADE_OUTPUT_STAG_EPOCH		12
#define CASCADE_CAND_CHANGE_FRACTION	0.10
#define CASCADE_CAND_STAG_EPOCH			12
#define CASCADE_MAX_OUT_EPOCH			150
#define CASCADE_MIN_OUT_EPOCH			50
#define CASCADE_MAX_CAND_EPOCH			150
#define CASCADE_MIN_CAND_EPOCH			50
#define CASCADE_NUM_CAND_GROUPS			2
#define BIT_FAIL_LIMIT					82

//#define CASCADE_CAND_LIMIT 				8192000
#define CASCADE_CAND_LIMIT				32767
#define CASCADE_WEIGHT_MULT				32767

//CASCADE_ACTIVATION_FUNCTIOS
#define CASCADE_ACTIV_FUNC_COUNT	 	10

#define CAF_1 			3
#define CAF_2 			5
#define CAF_3 			7
#define CAF_4 			8
#define CAF_5 			10
#define CAF_6 			11
#define CAF_7			14
#define CAF_8 			15
#define CAF_9			16
#define CAF_10			17

//CASCADE_ACTIVATION_STEEPNESSES_COUNT
#define CASCADE_ACTIVATION_STEEPNESSES_COUNT 4

#define CAS_1 2048
#define CAS_2 4096
#define CAS_3 6144
#define CAS_4 8192

//LAYER SIZES
#define L1	 3	
#define L2	 4
#define L3   2

